In [59]:
import torch
import torch.nn as nn
import torch.nn.functional as F


Net = nn.Sequential(nn.Linear(20,4), nn.ReLU(), nn.Linear(4,1))
X = torch.rand(64,20)
Net(X)
print(Net[2].state_dict())

print(Net[2].bias.grad)

print(Net)

OrderedDict([('weight', tensor([[-0.2034, -0.4003,  0.3164, -0.4063]])), ('bias', tensor([-0.3595]))])
None
Sequential(
  (0): Linear(in_features=20, out_features=4, bias=True)
  (1): ReLU()
  (2): Linear(in_features=4, out_features=1, bias=True)
)


In [60]:
print(Net[2].weight)
print()
print(Net[2].weight.grad)

Parameter containing:
tensor([[-0.2034, -0.4003,  0.3164, -0.4063]], requires_grad=True)

None


每个参数都表示为参数类的一个实例，是复合的对象：包含值、梯度和额外信息。

In [61]:
for name, param in Net.named_parameters():
    print(f"参数名字: {name}, 形状: {param.shape}")
    print(param)

参数名字: 0.weight, 形状: torch.Size([4, 20])
Parameter containing:
tensor([[ 0.0531, -0.1428,  0.0901,  0.0792, -0.0300,  0.0056, -0.0477, -0.0196,
          0.1101,  0.0203,  0.1369,  0.0659,  0.2112,  0.1281, -0.1667, -0.0479,
          0.0241, -0.2110,  0.0214,  0.0651],
        [ 0.0593, -0.0043,  0.1232, -0.0234,  0.0377, -0.0998,  0.0470, -0.1030,
         -0.0897, -0.1811, -0.1470,  0.0896,  0.2066, -0.0671,  0.1082,  0.0531,
         -0.1068, -0.1408, -0.1760, -0.0347],
        [-0.0261,  0.0268, -0.1746,  0.2160,  0.0431, -0.2125,  0.2158, -0.2187,
          0.1615,  0.0243, -0.0255, -0.1965,  0.0274,  0.2230,  0.0125, -0.1642,
         -0.1204, -0.1034, -0.0438, -0.0453],
        [-0.0213, -0.1502, -0.1276,  0.1307, -0.1057,  0.0275, -0.0058, -0.0767,
          0.0823, -0.0429, -0.2192, -0.1661,  0.0406,  0.1828,  0.1975, -0.2052,
          0.2234, -0.1916,  0.0388, -0.1405]], requires_grad=True)
参数名字: 0.bias, 形状: torch.Size([4])
Parameter containing:
tensor([ 0.2235,  0.0045,  0.

In [62]:
def block1():
    return nn.Sequential(nn.Linear(2,4), nn.ReLU(), nn.Linear(4,2), nn.ReLU())


def block2():
    Net = nn.Sequential()
    for i in range(4):
        Net.add_module(f'block{i}',block1())
    return Net

BigNet = nn.Sequential(block2(), nn.Linear(2,1))
print(BigNet)
# print(BigNet[0])

Sequential(
  (0): Sequential(
    (block0): Sequential(
      (0): Linear(in_features=2, out_features=4, bias=True)
      (1): ReLU()
      (2): Linear(in_features=4, out_features=2, bias=True)
      (3): ReLU()
    )
    (block1): Sequential(
      (0): Linear(in_features=2, out_features=4, bias=True)
      (1): ReLU()
      (2): Linear(in_features=4, out_features=2, bias=True)
      (3): ReLU()
    )
    (block2): Sequential(
      (0): Linear(in_features=2, out_features=4, bias=True)
      (1): ReLU()
      (2): Linear(in_features=4, out_features=2, bias=True)
      (3): ReLU()
    )
    (block3): Sequential(
      (0): Linear(in_features=2, out_features=4, bias=True)
      (1): ReLU()
      (2): Linear(in_features=4, out_features=2, bias=True)
      (3): ReLU()
    )
  )
  (1): Linear(in_features=2, out_features=1, bias=True)
)


In [63]:
# print(BigNet[0])
print(BigNet[1])

Linear(in_features=2, out_features=1, bias=True)


In [64]:
print(BigNet[0][2])

Sequential(
  (0): Linear(in_features=2, out_features=4, bias=True)
  (1): ReLU()
  (2): Linear(in_features=4, out_features=2, bias=True)
  (3): ReLU()
)


In [65]:
print(BigNet[0][2][2].weight)

Parameter containing:
tensor([[ 0.3287,  0.3918, -0.0575,  0.1200],
        [ 0.1491, -0.4860, -0.4953, -0.0164]], requires_grad=True)
