In [133]:
import torch
import torch.nn as nn
from d2l import torch as d2l


def con2d(X, K):
    X_kuan, X_chang = X.shape
    K_kuan, K_chang = K.shape
    Y = torch.zeros((X_kuan - K_kuan + 1, X_chang - K_chang + 1))
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            Y[i, j] = (X[i:i+K_kuan, j:j+K_chang]*K).sum()
    return Y

In [134]:
X = torch.tensor([[3,3,3], [1,1,1], [98,103,31]])
K = torch.tensor([[2,2], [4,4], [0,0]])
print(con2d(X, K))

tensor([[20., 20.]])


In [135]:
class Conv2d(nn.Module):
    def __init__(self, kernel_size):
        super().__init__()
        self.params = nn.Parameter(kernel_size)
        self.bias = nn.Parameter()

    def forward(self, X):
        return con2d(X, self.params) + self.bias

In [136]:
X = torch.ones((6, 8))
X[:, 2:6] = 0
X

tensor([[1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.]])

In [137]:
K = torch.tensor([[1.0, -1.0]])
Y = con2d(X, K)
Y

tensor([[ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.]])

In [138]:
X.T

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [139]:
Y = con2d(X.T, K)
Y

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

上面代码conv2d是互相关操作：权重 K 和输入 X 的对应小块进行元素相乘，然后求和。
卷积需要先将 K 进行两次翻转：水平翻转，垂直翻转。然后再进行。
在DL训练中实际上这种两次翻转没有区别，所以现在DL的卷积全部使用的是互相关。