多输入通道互相关运算就是：将表征向量每一维提取出对应的二维层进行互相关，然后逐元素相加

In [30]:
import torch
from d2l import torch as d2l


def con2d_multi(X, K):
    return sum(d2l.corr2d(x,k) for x, k in zip(X,K))


X = torch.tensor([[[0.0, 1.0, 2.0], [3.0, 4.0, 5.0], [6.0, 7.0, 8.0]],
               [[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]]])
K = torch.tensor([[[0.0, 1.0], [2.0, 3.0]], [[1.0, 2.0], [3.0, 4.0]]])


con2d_multi(X, K)

tensor([[ 56.,  72.],
        [104., 120.]])

In [31]:
def con2d_multi_out(X, K):
    return torch.stack([con2d_multi(X, k) for k in K], 0)


K = torch.stack([K, K+1, K+2])
con2d_multi_out(X, K)

tensor([[[ 56.,  72.],
         [104., 120.]],

        [[ 76., 100.],
         [148., 172.]],

        [[ 96., 128.],
         [192., 224.]]])

In [32]:
def con2d_multi_out_11(X, K):
    c_i, h, w = X.shape
    c_o = K.shape[0]
    X = X.reshape((c_i, h*w))
    K = K.reshape((c_o, c_i))
    Y = torch.matmul(K, X)
    return Y.reshape((c_o, h, w))


X = torch.tensor([[[0.0, 1.0, 2.0], [3.0, 4.0, 5.0], [6.0, 7.0, 8.0]],
               [[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]]])
c_i, h, w = X.shape
print(c_i)
print(h)
print(w)

2
3
3


In [33]:
K = torch.tensor([[[[1.0]],[[1.0]]],[[[1.0]],[[1.0]]]])
c_o, c_i, h, w = K.shape
print(c_o)
print(c_i)
print(h)
print(w)

2
2
1
1


In [34]:
con2d_multi_out_11(X, K)

tensor([[[ 1.,  3.,  5.],
         [ 7.,  9., 11.],
         [13., 15., 17.]],

        [[ 1.,  3.,  5.],
         [ 7.,  9., 11.],
         [13., 15., 17.]]])