In [39]:
import torch
import torch.nn as nn

X = torch.arange(16, dtype=torch.float32).reshape((1, 1, 4, 4))
poll2d = nn.MaxPool2d(3)
poll2d(X)

tensor([[[[10.]]]])

In [40]:
poll2d = nn.MaxPool2d(3,3,1)
poll2d(X)

tensor([[[[ 5.,  7.],
          [13., 15.]]]])

In [41]:
X = torch.cat([X,X+1],1)
X.shape
X

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]],

         [[ 1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.],
          [ 9., 10., 11., 12.],
          [13., 14., 15., 16.]]]])

In [42]:
poll2d(X)

tensor([[[[ 5.,  7.],
          [13., 15.]],

         [[ 6.,  8.],
          [14., 16.]]]])