In [10]:
import torch
import torch.nn as nn
import torch.nn.functional as F


class nonparams_layer(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, X):
        return X - X.mean()
    

class selfdefine_layer(nn.Module):
    def __init__(self, input_dim, output_dim):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(input_dim, output_dim))
        self.bias = nn.Parameter(torch.randn(output_dim))

    def forward(self, X):
        X = torch.matmul(X, self.weight) + self.bias
        return F.relu(X)
    

net = nn.Sequential(selfdefine_layer(8,8), nonparams_layer())
y = net(torch.rand(4,8))
print(y)

tensor([[ 0.3735,  1.7634,  3.0608, -0.2776, -1.0591, -0.3189,  0.6840, -1.0591],
        [-0.1149,  1.1563,  2.7719, -1.0591, -1.0591, -0.1221, -0.4342, -1.0591],
        [-0.5446,  1.5857,  2.1144, -1.0591, -1.0591,  0.2102,  0.1538, -1.0591],
        [-0.7059,  0.4759,  1.6765, -1.0591, -1.0591, -0.8274, -1.0306, -1.0591]],
       grad_fn=<SubBackward0>)


In [11]:
print(net[0].weight)
print(net[0].bias)

Parameter containing:
tensor([[-1.3358, -0.7747,  0.1768, -0.8576, -0.1775,  0.2183,  1.8248,  1.0529],
        [ 1.3741,  0.3367,  0.8387,  0.4182,  0.0756,  0.7477,  1.6599,  0.3717],
        [-0.2055, -0.5220,  0.7776, -1.9056, -1.0637, -1.0731, -0.0823, -0.0213],
        [ 0.0645,  0.7239,  0.9804,  0.6466, -0.5451, -1.4324,  0.2407, -1.5621],
        [ 0.5757,  0.9026,  0.2908,  1.2465, -1.4988, -0.3342, -0.4602, -1.4585],
        [ 0.2274,  0.6116,  0.4650,  0.0525,  0.6232,  0.0129,  1.6760, -0.3416],
        [-0.0088,  0.5261,  0.4933, -0.2822, -0.8827,  1.6780, -0.5834,  0.7031],
        [-0.7568,  0.0220, -0.8805,  0.6317, -0.3997,  0.6843,  0.3210, -0.6134]],
       requires_grad=True)
Parameter containing:
tensor([ 0.6453,  1.2885,  1.8877, -0.3882, -1.5233,  0.5774, -0.4750, -1.1654],
       requires_grad=True)
